server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    url: jdbc:h2:mem:example
    platform: h2

feign:
  client:
    config:
      default:
        requestInterceptors:
          -  work.lince.commons.rest.client.AuthenticationFeignInterceptor
      lince-resources:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        url: http://localhost:50001